#############################################################################
# Makefile for building: aprs_mapper_v2
# Generated by qmake (2.01a) (Qt 4.6.3) on: Wed Apr 20 14:39:46 2011
# Project:  aprs_mapper_v2.pro
# Template: app
# Command: /opt/qtsdk-2010.04/qt/bin/qmake -spec /opt/qtsdk-2010.04/qt/mkspecs/linux-g++ -unix CONFIG+=debug QMLJSDEBUGGER_PATH=/usr/local/Trolltech/qt-creator-2.1.0/share/qtcreator/qml/qmljsdebugger -o Makefile aprs_mapper_v2.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_SQL_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/opt/qtsdk-2010.04/qt/mkspecs/linux-g++ -I. -I/opt/qtsdk-2010.04/qt/include/QtCore -I/opt/qtsdk-2010.04/qt/include/QtNetwork -I/opt/qtsdk-2010.04/qt/include/QtGui -I/opt/qtsdk-2010.04/qt/include/QtXml -I/opt/qtsdk-2010.04/qt/include/QtSql -I/opt/qtsdk-2010.04/qt/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/opt/qtsdk-2010.04/qt/lib
LIBS          = $(SUBLIBS)  -L/opt/qtsdk-2010.04/qt/lib -lQtSql -L/opt/qtsdk-2010.04/qt/lib -lQtXml -lQtGui -L/usr/X11R6/lib -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /opt/qtsdk-2010.04/qt/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = aprsmain.cpp \
		point.cpp \
		map.cpp \
		mapgraphicsscene.cpp \
		connection.cpp \
		profilemenu.cpp \
		profile.cpp \
		parserthread.cpp \
		errorhandler.cpp \
		coordinate.cpp \
		main.cpp \
		overlay.cpp \
		parser.cpp \
		database.cpp \
		createnew.cpp \
		loadprofile.cpp \
		connectionmenu.cpp \
		aprs_parser.cpp \
		mydebug.cpp \
		about.cpp moc_aprsmain.cpp \
		moc_connection.cpp \
		moc_profilemenu.cpp \
		moc_profile.cpp \
		moc_point.cpp \
		moc_parserthread.cpp \
		moc_mapgraphicsscene.cpp \
		moc_map.cpp \
		moc_parser.cpp \
		moc_overlay.cpp \
		moc_database.cpp \
		moc_createnew.cpp \
		moc_loadprofile.cpp \
		moc_connectionmenu.cpp \
		moc_about.cpp
OBJECTS       = aprsmain.o \
		point.o \
		map.o \
		mapgraphicsscene.o \
		connection.o \
		profilemenu.o \
		profile.o \
		parserthread.o \
		errorhandler.o \
		coordinate.o \
		main.o \
		overlay.o \
		parser.o \
		database.o \
		createnew.o \
		loadprofile.o \
		connectionmenu.o \
		aprs_parser.o \
		mydebug.o \
		about.o \
		moc_aprsmain.o \
		moc_connection.o \
		moc_profilemenu.o \
		moc_profile.o \
		moc_point.o \
		moc_parserthread.o \
		moc_mapgraphicsscene.o \
		moc_map.o \
		moc_parser.o \
		moc_overlay.o \
		moc_database.o \
		moc_createnew.o \
		moc_loadprofile.o \
		moc_connectionmenu.o \
		moc_about.o
DIST          = /opt/qtsdk-2010.04/qt/mkspecs/common/g++.conf \
		/opt/qtsdk-2010.04/qt/mkspecs/common/unix.conf \
		/opt/qtsdk-2010.04/qt/mkspecs/common/linux.conf \
		/opt/qtsdk-2010.04/qt/mkspecs/qconfig.pri \
		/opt/qtsdk-2010.04/qt/mkspecs/features/qt_functions.prf \
		/opt/qtsdk-2010.04/qt/mkspecs/features/qt_config.prf \
		/opt/qtsdk-2010.04/qt/mkspecs/features/exclusive_builds.prf \
		/opt/qtsdk-2010.04/qt/mkspecs/features/default_pre.prf \
		/opt/qtsdk-2010.04/qt/mkspecs/features/debug.prf \
		/opt/qtsdk-2010.04/qt/mkspecs/features/default_post.prf \
		/opt/qtsdk-2010.04/qt/mkspecs/features/warn_on.prf \
		/opt/qtsdk-2010.04/qt/mkspecs/features/qt.prf \
		/opt/qtsdk-2010.04/qt/mkspecs/features/unix/thread.prf \
		/opt/qtsdk-2010.04/qt/mkspecs/features/moc.prf \
		/opt/qtsdk-2010.04/qt/mkspecs/features/resources.prf \
		/opt/qtsdk-2010.04/qt/mkspecs/features/uic.prf \
		/opt/qtsdk-2010.04/qt/mkspecs/features/yacc.prf \
		/opt/qtsdk-2010.04/qt/mkspecs/features/lex.prf \
		/opt/qtsdk-2010.04/qt/mkspecs/features/include_source_dir.prf \
		aprs_mapper_v2.pro
QMAKE_TARGET  = aprs_mapper_v2
DESTDIR       = 
TARGET        = aprs_mapper_v2

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_aprsmain.h ui_profilemenu.h ui_createnew.h ui_loadprofile.h ui_connectionmenu.h ui_about.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: aprs_mapper_v2.pro  /opt/qtsdk-2010.04/qt/mkspecs/linux-g++/qmake.conf /opt/qtsdk-2010.04/qt/mkspecs/common/g++.conf \
		/opt/qtsdk-2010.04/qt/mkspecs/common/unix.conf \
		/opt/qtsdk-2010.04/qt/mkspecs/common/linux.conf \
		/opt/qtsdk-2010.04/qt/mkspecs/qconfig.pri \
		/opt/qtsdk-2010.04/qt/mkspecs/features/qt_functions.prf \
		/opt/qtsdk-2010.04/qt/mkspecs/features/qt_config.prf \
		/opt/qtsdk-2010.04/qt/mkspecs/features/exclusive_builds.prf \
		/opt/qtsdk-2010.04/qt/mkspecs/features/default_pre.prf \
		/opt/qtsdk-2010.04/qt/mkspecs/features/debug.prf \
		/opt/qtsdk-2010.04/qt/mkspecs/features/default_post.prf \
		/opt/qtsdk-2010.04/qt/mkspecs/features/warn_on.prf \
		/opt/qtsdk-2010.04/qt/mkspecs/features/qt.prf \
		/opt/qtsdk-2010.04/qt/mkspecs/features/unix/thread.prf \
		/opt/qtsdk-2010.04/qt/mkspecs/features/moc.prf \
		/opt/qtsdk-2010.04/qt/mkspecs/features/resources.prf \
		/opt/qtsdk-2010.04/qt/mkspecs/features/uic.prf \
		/opt/qtsdk-2010.04/qt/mkspecs/features/yacc.prf \
		/opt/qtsdk-2010.04/qt/mkspecs/features/lex.prf \
		/opt/qtsdk-2010.04/qt/mkspecs/features/include_source_dir.prf \
		/opt/qtsdk-2010.04/qt/lib/libQtSql.prl \
		/opt/qtsdk-2010.04/qt/lib/libQtCore.prl \
		/opt/qtsdk-2010.04/qt/lib/libQtXml.prl \
		/opt/qtsdk-2010.04/qt/lib/libQtGui.prl \
		/opt/qtsdk-2010.04/qt/lib/libQtNetwork.prl
	$(QMAKE) -spec /opt/qtsdk-2010.04/qt/mkspecs/linux-g++ -unix CONFIG+=debug QMLJSDEBUGGER_PATH=/usr/local/Trolltech/qt-creator-2.1.0/share/qtcreator/qml/qmljsdebugger -o Makefile aprs_mapper_v2.pro
/opt/qtsdk-2010.04/qt/mkspecs/common/g++.conf:
/opt/qtsdk-2010.04/qt/mkspecs/common/unix.conf:
/opt/qtsdk-2010.04/qt/mkspecs/common/linux.conf:
/opt/qtsdk-2010.04/qt/mkspecs/qconfig.pri:
/opt/qtsdk-2010.04/qt/mkspecs/features/qt_functions.prf:
/opt/qtsdk-2010.04/qt/mkspecs/features/qt_config.prf:
/opt/qtsdk-2010.04/qt/mkspecs/features/exclusive_builds.prf:
/opt/qtsdk-2010.04/qt/mkspecs/features/default_pre.prf:
/opt/qtsdk-2010.04/qt/mkspecs/features/debug.prf:
/opt/qtsdk-2010.04/qt/mkspecs/features/default_post.prf:
/opt/qtsdk-2010.04/qt/mkspecs/features/warn_on.prf:
/opt/qtsdk-2010.04/qt/mkspecs/features/qt.prf:
/opt/qtsdk-2010.04/qt/mkspecs/features/unix/thread.prf:
/opt/qtsdk-2010.04/qt/mkspecs/features/moc.prf:
/opt/qtsdk-2010.04/qt/mkspecs/features/resources.prf:
/opt/qtsdk-2010.04/qt/mkspecs/features/uic.prf:
/opt/qtsdk-2010.04/qt/mkspecs/features/yacc.prf:
/opt/qtsdk-2010.04/qt/mkspecs/features/lex.prf:
/opt/qtsdk-2010.04/qt/mkspecs/features/include_source_dir.prf:
/opt/qtsdk-2010.04/qt/lib/libQtSql.prl:
/opt/qtsdk-2010.04/qt/lib/libQtCore.prl:
/opt/qtsdk-2010.04/qt/lib/libQtXml.prl:
/opt/qtsdk-2010.04/qt/lib/libQtGui.prl:
/opt/qtsdk-2010.04/qt/lib/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -spec /opt/qtsdk-2010.04/qt/mkspecs/linux-g++ -unix CONFIG+=debug QMLJSDEBUGGER_PATH=/usr/local/Trolltech/qt-creator-2.1.0/share/qtcreator/qml/qmljsdebugger -o Makefile aprs_mapper_v2.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/aprs_mapper_v21.0.0 || $(MKDIR) .tmp/aprs_mapper_v21.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/aprs_mapper_v21.0.0/ && $(COPY_FILE) --parents aprsmain.h connection.h profilemenu.h profile.h point.h parserthread.h mapgraphicsscene.h map.h errorhandler.h coordinate.h parser.h overlay.h packettypes.h database.h createnew.h loadprofile.h connectionmenu.h aprs_parser.h stringify.h mydebug.h about.h .tmp/aprs_mapper_v21.0.0/ && $(COPY_FILE) --parents aprsmain.cpp point.cpp map.cpp mapgraphicsscene.cpp connection.cpp profilemenu.cpp profile.cpp parserthread.cpp errorhandler.cpp coordinate.cpp main.cpp overlay.cpp parser.cpp database.cpp createnew.cpp loadprofile.cpp connectionmenu.cpp aprs_parser.cpp mydebug.cpp about.cpp .tmp/aprs_mapper_v21.0.0/ && $(COPY_FILE) --parents aprsmain.ui profilemenu.ui createnew.ui loadprofile.ui connectionmenu.ui about.ui .tmp/aprs_mapper_v21.0.0/ && (cd `dirname .tmp/aprs_mapper_v21.0.0` && $(TAR) aprs_mapper_v21.0.0.tar aprs_mapper_v21.0.0 && $(COMPRESS) aprs_mapper_v21.0.0.tar) && $(MOVE) `dirname .tmp/aprs_mapper_v21.0.0`/aprs_mapper_v21.0.0.tar.gz . && $(DEL_FILE) -r .tmp/aprs_mapper_v21.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_aprsmain.cpp moc_connection.cpp moc_profilemenu.cpp moc_profile.cpp moc_point.cpp moc_parserthread.cpp moc_mapgraphicsscene.cpp moc_map.cpp moc_parser.cpp moc_overlay.cpp moc_database.cpp moc_createnew.cpp moc_loadprofile.cpp moc_connectionmenu.cpp moc_about.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_aprsmain.cpp moc_connection.cpp moc_profilemenu.cpp moc_profile.cpp moc_point.cpp moc_parserthread.cpp moc_mapgraphicsscene.cpp moc_map.cpp moc_parser.cpp moc_overlay.cpp moc_database.cpp moc_createnew.cpp moc_loadprofile.cpp moc_connectionmenu.cpp moc_about.cpp
moc_aprsmain.cpp: map.h \
		errorhandler.h \
		point.h \
		profile.h \
		coordinate.h \
		aprs_parser.h \
		overlay.h \
		packettypes.h \
		mapgraphicsscene.h \
		parserthread.h \
		connection.h \
		parser.h \
		database.h \
		aprsmain.h
	/opt/qtsdk-2010.04/qt/bin/moc $(DEFINES) $(INCPATH) aprsmain.h -o moc_aprsmain.cpp

moc_connection.cpp: errorhandler.h \
		point.h \
		profile.h \
		coordinate.h \
		aprs_parser.h \
		parser.h \
		packettypes.h \
		connection.h
	/opt/qtsdk-2010.04/qt/bin/moc $(DEFINES) $(INCPATH) connection.h -o moc_connection.cpp

moc_profilemenu.cpp: profile.h \
		errorhandler.h \
		coordinate.h \
		connectionmenu.h \
		profilemenu.h
	/opt/qtsdk-2010.04/qt/bin/moc $(DEFINES) $(INCPATH) profilemenu.h -o moc_profilemenu.cpp

moc_profile.cpp: errorhandler.h \
		coordinate.h \
		profile.h
	/opt/qtsdk-2010.04/qt/bin/moc $(DEFINES) $(INCPATH) profile.h -o moc_profile.cpp

moc_point.cpp: profile.h \
		errorhandler.h \
		coordinate.h \
		aprs_parser.h \
		point.h
	/opt/qtsdk-2010.04/qt/bin/moc $(DEFINES) $(INCPATH) point.h -o moc_point.cpp

moc_parserthread.cpp: connection.h \
		errorhandler.h \
		point.h \
		profile.h \
		coordinate.h \
		aprs_parser.h \
		parser.h \
		packettypes.h \
		parserthread.h
	/opt/qtsdk-2010.04/qt/bin/moc $(DEFINES) $(INCPATH) parserthread.h -o moc_parserthread.cpp

moc_mapgraphicsscene.cpp: mapgraphicsscene.h
	/opt/qtsdk-2010.04/qt/bin/moc $(DEFINES) $(INCPATH) mapgraphicsscene.h -o moc_mapgraphicsscene.cpp

moc_map.cpp: errorhandler.h \
		point.h \
		profile.h \
		coordinate.h \
		aprs_parser.h \
		overlay.h \
		packettypes.h \
		map.h
	/opt/qtsdk-2010.04/qt/bin/moc $(DEFINES) $(INCPATH) map.h -o moc_map.cpp

moc_parser.cpp: packettypes.h \
		aprs_parser.h \
		parser.h
	/opt/qtsdk-2010.04/qt/bin/moc $(DEFINES) $(INCPATH) parser.h -o moc_parser.cpp

moc_overlay.cpp: overlay.h
	/opt/qtsdk-2010.04/qt/bin/moc $(DEFINES) $(INCPATH) overlay.h -o moc_overlay.cpp

moc_database.cpp: packettypes.h \
		aprs_parser.h \
		point.h \
		profile.h \
		errorhandler.h \
		coordinate.h \
		database.h
	/opt/qtsdk-2010.04/qt/bin/moc $(DEFINES) $(INCPATH) database.h -o moc_database.cpp

moc_createnew.cpp: createnew.h
	/opt/qtsdk-2010.04/qt/bin/moc $(DEFINES) $(INCPATH) createnew.h -o moc_createnew.cpp

moc_loadprofile.cpp: loadprofile.h
	/opt/qtsdk-2010.04/qt/bin/moc $(DEFINES) $(INCPATH) loadprofile.h -o moc_loadprofile.cpp

moc_connectionmenu.cpp: connectionmenu.h
	/opt/qtsdk-2010.04/qt/bin/moc $(DEFINES) $(INCPATH) connectionmenu.h -o moc_connectionmenu.cpp

moc_about.cpp: about.h
	/opt/qtsdk-2010.04/qt/bin/moc $(DEFINES) $(INCPATH) about.h -o moc_about.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_aprsmain.h ui_profilemenu.h ui_createnew.h ui_loadprofile.h ui_connectionmenu.h ui_about.h
compiler_uic_clean:
	-$(DEL_FILE) ui_aprsmain.h ui_profilemenu.h ui_createnew.h ui_loadprofile.h ui_connectionmenu.h ui_about.h
ui_aprsmain.h: aprsmain.ui
	/opt/qtsdk-2010.04/qt/bin/uic aprsmain.ui -o ui_aprsmain.h

ui_profilemenu.h: profilemenu.ui
	/opt/qtsdk-2010.04/qt/bin/uic profilemenu.ui -o ui_profilemenu.h

ui_createnew.h: createnew.ui
	/opt/qtsdk-2010.04/qt/bin/uic createnew.ui -o ui_createnew.h

ui_loadprofile.h: loadprofile.ui
	/opt/qtsdk-2010.04/qt/bin/uic loadprofile.ui -o ui_loadprofile.h

ui_connectionmenu.h: connectionmenu.ui
	/opt/qtsdk-2010.04/qt/bin/uic connectionmenu.ui -o ui_connectionmenu.h

ui_about.h: about.ui
	/opt/qtsdk-2010.04/qt/bin/uic about.ui -o ui_about.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

aprsmain.o: aprsmain.cpp aprsmain.h \
		map.h \
		errorhandler.h \
		point.h \
		profile.h \
		coordinate.h \
		aprs_parser.h \
		overlay.h \
		packettypes.h \
		mapgraphicsscene.h \
		parserthread.h \
		connection.h \
		parser.h \
		database.h \
		connectionmenu.h \
		ui_aprsmain.h \
		profilemenu.h \
		createnew.h \
		loadprofile.h \
		about.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o aprsmain.o aprsmain.cpp

point.o: point.cpp profile.h \
		errorhandler.h \
		coordinate.h \
		point.h \
		aprs_parser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o point.o point.cpp

map.o: map.cpp map.h \
		errorhandler.h \
		point.h \
		profile.h \
		coordinate.h \
		aprs_parser.h \
		overlay.h \
		packettypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o map.o map.cpp

mapgraphicsscene.o: mapgraphicsscene.cpp mapgraphicsscene.h \
		errorhandler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mapgraphicsscene.o mapgraphicsscene.cpp

connection.o: connection.cpp connection.h \
		errorhandler.h \
		point.h \
		profile.h \
		coordinate.h \
		aprs_parser.h \
		parser.h \
		packettypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o connection.o connection.cpp

profilemenu.o: profilemenu.cpp connectionmenu.h \
		profilemenu.h \
		profile.h \
		errorhandler.h \
		coordinate.h \
		ui_profilemenu.h \
		createnew.h \
		aprsmain.h \
		map.h \
		point.h \
		aprs_parser.h \
		overlay.h \
		packettypes.h \
		mapgraphicsscene.h \
		parserthread.h \
		connection.h \
		parser.h \
		database.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o profilemenu.o profilemenu.cpp

profile.o: profile.cpp profile.h \
		errorhandler.h \
		coordinate.h \
		createnew.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o profile.o profile.cpp

parserthread.o: parserthread.cpp parserthread.h \
		connection.h \
		errorhandler.h \
		point.h \
		profile.h \
		coordinate.h \
		aprs_parser.h \
		parser.h \
		packettypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o parserthread.o parserthread.cpp

errorhandler.o: errorhandler.cpp profile.h \
		errorhandler.h \
		coordinate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o errorhandler.o errorhandler.cpp

coordinate.o: coordinate.cpp coordinate.h \
		errorhandler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o coordinate.o coordinate.cpp

main.o: main.cpp aprsmain.h \
		map.h \
		errorhandler.h \
		point.h \
		profile.h \
		coordinate.h \
		aprs_parser.h \
		overlay.h \
		packettypes.h \
		mapgraphicsscene.h \
		parserthread.h \
		connection.h \
		parser.h \
		database.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

overlay.o: overlay.cpp overlay.h \
		coordinate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o overlay.o overlay.cpp

parser.o: parser.cpp parser.h \
		packettypes.h \
		aprs_parser.h \
		errorhandler.h \
		stringify.h \
		point.h \
		profile.h \
		coordinate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o parser.o parser.cpp

database.o: database.cpp database.h \
		packettypes.h \
		aprs_parser.h \
		point.h \
		profile.h \
		errorhandler.h \
		coordinate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o database.o database.cpp

createnew.o: createnew.cpp createnew.h \
		ui_createnew.h \
		profile.h \
		errorhandler.h \
		coordinate.h \
		profilemenu.h \
		connectionmenu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o createnew.o createnew.cpp

loadprofile.o: loadprofile.cpp loadprofile.h \
		profile.h \
		errorhandler.h \
		coordinate.h \
		ui_loadprofile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o loadprofile.o loadprofile.cpp

connectionmenu.o: connectionmenu.cpp connectionmenu.h \
		ui_connectionmenu.h \
		profile.h \
		errorhandler.h \
		coordinate.h \
		profilemenu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o connectionmenu.o connectionmenu.cpp

aprs_parser.o: aprs_parser.cpp mydebug.h \
		stringify.h \
		aprs_parser.h \
		packettypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o aprs_parser.o aprs_parser.cpp

mydebug.o: mydebug.cpp mydebug.h \
		packettypes.h \
		aprs_parser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mydebug.o mydebug.cpp

about.o: about.cpp about.h \
		ui_about.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o about.o about.cpp

moc_aprsmain.o: moc_aprsmain.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_aprsmain.o moc_aprsmain.cpp

moc_connection.o: moc_connection.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_connection.o moc_connection.cpp

moc_profilemenu.o: moc_profilemenu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_profilemenu.o moc_profilemenu.cpp

moc_profile.o: moc_profile.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_profile.o moc_profile.cpp

moc_point.o: moc_point.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_point.o moc_point.cpp

moc_parserthread.o: moc_parserthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_parserthread.o moc_parserthread.cpp

moc_mapgraphicsscene.o: moc_mapgraphicsscene.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mapgraphicsscene.o moc_mapgraphicsscene.cpp

moc_map.o: moc_map.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_map.o moc_map.cpp

moc_parser.o: moc_parser.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_parser.o moc_parser.cpp

moc_overlay.o: moc_overlay.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_overlay.o moc_overlay.cpp

moc_database.o: moc_database.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_database.o moc_database.cpp

moc_createnew.o: moc_createnew.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_createnew.o moc_createnew.cpp

moc_loadprofile.o: moc_loadprofile.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_loadprofile.o moc_loadprofile.cpp

moc_connectionmenu.o: moc_connectionmenu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_connectionmenu.o moc_connectionmenu.cpp

moc_about.o: moc_about.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_about.o moc_about.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

